# Cooperation for compounds from other members: consumption overlap

In [1]:
import pandas as pd
import json
import seaborn as sns
import numpy as np

import networkx as nx

from pyvis.network import Network

import sys

sys.path.append("../functions/")
import networks

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
with open("../data/Venturelli2018/generated/metid2metname.json") as json_file:
    metid2metname = json.load(json_file)

results = pd.read_csv("../output/Venturelli2018/results_steadiercom/NONE_abundance.tsv",sep="\t")

results["mass_rate*frequency"] = results["frequency"]*results["mass_rate"]

In [4]:
results

,donor,receiver,compound,mass_rate,rate,frequency,community,medium,mass_rate*frequency
0,Faecalibacterium_prausnitzii_A2_165,environment,M_hxan__91__e__93__,8.368614e-02,6.148361e-01,0.045,NONE,LB_extend,3.765876e-03
1,Faecalibacterium_prausnitzii_A2_165,environment,M_rbflvrd__91__e__93__,7.425670e-02,1.962496e-01,0.644,NONE,LB_extend,4.782131e-02
2,environment,Bacteroides_uniformis_ATCC_8492,M_malt__91__e__93__,5.267861e-02,1.538980e-01,0.977,NONE,LB_extend,5.146700e-02
3,environment,Faecalibacterium_prausnitzii_A2_165,M_ribflv__91__e__93__,4.762329e-02,1.265355e-01,1.000,NONE,LB_extend,4.762329e-02
4,Bacteroides_uniformis_ATCC_8492,environment,M_succ__91__e__93__,4.489770e-02,3.868091e-01,0.923,NONE,LB_extend,4.144058e-02
...,...,...,...,...,...,...,...,...,...
2226,Desulfovibrio_piger_ATCC_29098,Bacteroides_ovatus_ATCC_8483,M_for__91__e__93__,1.287264e-09,2.859482e-08,0.001,NONE,LB_extend,1.287264e-12
2227,environment,Eubacterium_rectale_ATCC_33656,M_o2__91__e__93__,6.602988e-10,2.063511e-08,0.012,NONE,LB_extend,7.923586e-12
2228,Eubacterium_rectale_ATCC_33656,Desulfovibrio_piger_ATCC_29098,M_co2__91__e__93__,5.980662e-10,1.358948e-08,0.001,NONE,LB_extend,5.980662e-13
2229,Clostridium_hiranonis_TO_931_DSM_13275,Desulfovibrio_piger_ATCC_29098,M_co2__91__e__93__,4.628424e-10,1.051687e-08,0.001,NONE,LB_extend,4.628424e-13
2230,Desulfovibrio_piger_ATCC_29098,Eubacterium_rectale_ATCC_33656,M_for__91__e__93__,3.854907e-10,8.563148e-09,0.001,NONE,LB_extend,3.854907e-13

## Cooperation based on COUNT (Only metabolites from metabolomics + freq_cutoff=0 !)

In [5]:

network_data = networks.cooperation_network_data(results,metabolomics_mets_only=True,use_count=True, freq_cutoff=0)

In [6]:
network_data.max()

np.int64(5)

In [7]:
network_data.min()

np.int64(1)

**Network topological properties**


- **Betweeness_centrality**: Sum of shortest paths that pass through node i
- **Degree centrality**: The fraction of nodes that node i is connected to. 
- **Eigenvector centrality**: Higher if node i is connected to other well connected notes.

In [8]:
centrality_metrics_SP = networks.cooperation_centrality_metrics(network_data).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Eggerthella_lenta_DSM_2243,0.000000,1.232033
Faecalibacterium_prausnitzii_A2_165,0.052778,1.463855
Bacteroides_vulgatus_ATCC_8482,0.000000,1.542857
Bacteroides_ovatus_ATCC_8483,0.027778,1.572816
Eubacterium_rectale_ATCC_33656,0.027778,1.583062
Collinsella_aerofaciens_ATCC_25986,0.013889,1.609272
Desulfovibrio_piger_ATCC_29098,0.061111,1.614618
Bacteroides_uniformis_ATCC_8492,0.097222,1.625418
Bacteroides_thetaiotaomicron_VPI_5482,0.005556,1.670103
Blautia_hydrogenotrophica_DSM_10507,0.000000,1.675862
Clostridium_hiranonis_TO_931_DSM_13275,0.058333,1.928571

In [9]:
centrality_metrics_notSP = networks.cooperation_centrality_metrics(network_data,SP_centrality=False).sort_values("degree (data)")
centrality_metrics_notSP

                                        degree (data)  eigenvector (data)
Eggerthella_lenta_DSM_2243                         10            0.144988
Collinsella_aerofaciens_ATCC_25986                 21            0.233544
Blautia_hydrogenotrophica_DSM_10507                28            0.286060
Bacteroides_vulgatus_ATCC_8482                     31            0.323020
Eubacterium_rectale_ATCC_33656                     37            0.282116
Desulfovibrio_piger_ATCC_29098                     39            0.299022
Bacteroides_ovatus_ATCC_8483                       40            0.293527
Clostridium_hiranonis_TO_931_DSM_13275             48            0.420462
Bacteroides_thetaiotaomicron_VPI_5482              49            0.374528
Faecalibacterium_prausnitzii_A2_165                51            0.232233
Bacteroides_uniformis_ATCC_8492                    54            0.334830

In [10]:
closeness_centrality_met = centrality_metrics_SP["closeness (1/data)"]

In [11]:
net = networks.cooperation_network(network_data,closeness_centrality_met=closeness_centrality_met)
net.show("network_file.html")

network_file.html

In [12]:
net = networks.cooperation_network(network_data,closeness_centrality_met=closeness_centrality_met,cutoff=3)
net.show("network_file.html")

network_file.html

## Cooperation based on COUNT (Only metabolites from metabolomics + freq_cutoff = 0.1 !!)

In [13]:

network_data = networks.cooperation_network_data(results,metabolomics_mets_only=True,use_count=True,freq_cutoff=0.1)

In [14]:
network_data.max()

np.int64(3)

In [15]:
network_data.min()

np.int64(1)

**Network topological properties**


- **Betweeness_centrality**: Sum of shortest paths that pass through node i
- **Degree centrality**: The fraction of nodes that node i is connected to. 
- **Eigenvector centrality**: Higher if node i is connected to other well connected notes.

In [16]:
centrality_metrics_SP = networks.cooperation_centrality_metrics(network_data).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Bacteroides_ovatus_ATCC_8483,0.105556,0.263158
Faecalibacterium_prausnitzii_A2_165,0.022222,0.277778
Bacteroides_vulgatus_ATCC_8482,0.005556,0.312500
Eubacterium_rectale_ATCC_33656,0.027778,0.312500
Collinsella_aerofaciens_ATCC_25986,0.011111,0.342857
Blautia_hydrogenotrophica_DSM_10507,0.016667,0.400000
Desulfovibrio_piger_ATCC_29098,0.088889,0.416667
Bacteroides_uniformis_ATCC_8492,0.000000,0.450000
Eggerthella_lenta_DSM_2243,0.000000,0.457143
Bacteroides_thetaiotaomicron_VPI_5482,0.000000,0.480000
Clostridium_hiranonis_TO_931_DSM_13275,0.227778,0.555556

In [17]:
centrality_metrics_notSP = networks.cooperation_centrality_metrics(network_data,SP_centrality=False).sort_values("degree (data)")
centrality_metrics_notSP

                                        degree (data)  eigenvector (data)
Collinsella_aerofaciens_ATCC_25986                  2            0.171004
Eggerthella_lenta_DSM_2243                          3            0.381494
Blautia_hydrogenotrophica_DSM_10507                 4            0.360794
Bacteroides_uniformis_ATCC_8492                     4            0.267732
Bacteroides_vulgatus_ATCC_8482                      5            0.162525
Bacteroides_thetaiotaomicron_VPI_5482               5            0.335362
Desulfovibrio_piger_ATCC_29098                      6            0.428713
Faecalibacterium_prausnitzii_A2_165                 7            0.171004
Eubacterium_rectale_ATCC_33656                      8            0.238923
Bacteroides_ovatus_ATCC_8483                        9            0.170276
Clostridium_hiranonis_TO_931_DSM_13275             11            0.430546

In [18]:
closeness_centrality_met = centrality_metrics_SP["closeness (1/data)"]

In [19]:
net = networks.cooperation_network(network_data,closeness_centrality_met=closeness_centrality_met)
net.show("network_file.html")

network_file.html

## Cooperation based on COUNT (All metabolites + freq_cutoff=0.1!!)

In [21]:

network_data = networks.cooperation_network_data(results,metabolomics_mets_only=False,use_count=True,freq_cutoff=0.1)

In [22]:
network_data.max()

np.int64(5)

In [23]:
network_data.min()

np.int64(1)

**Network topological properties**


- **Betweeness_centrality**: Sum of shortest paths that pass through node i
- **Degree centrality**: The fraction of nodes that node i is connected to. 
- **Eigenvector centrality**: Higher if node i is connected to other well connected notes.

In [24]:
centrality_metrics_SP = networks.cooperation_centrality_metrics(network_data).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Eubacterium_rectale_ATCC_33656,0.000000,1.754386
Bacteroides_uniformis_ATCC_8492,0.002778,1.807229
Blautia_hydrogenotrophica_DSM_10507,0.000000,2.105263
Bacteroides_ovatus_ATCC_8483,0.089815,2.166065
Bacteroides_thetaiotaomicron_VPI_5482,0.006481,2.325581
Clostridium_hiranonis_TO_931_DSM_13275,0.053704,2.400000
Faecalibacterium_prausnitzii_A2_165,0.113889,2.419355
Bacteroides_vulgatus_ATCC_8482,0.022222,2.542373
Desulfovibrio_piger_ATCC_29098,0.016667,3.296703
Collinsella_aerofaciens_ATCC_25986,0.011111,3.333333
Eggerthella_lenta_DSM_2243,0.055556,3.529412

In [25]:
centrality_metrics_notSP = networks.cooperation_centrality_metrics(network_data,SP_centrality=False).sort_values("degree (data)")
centrality_metrics_notSP

                                        degree (data)  eigenvector (data)
Bacteroides_uniformis_ATCC_8492                    43            0.203639
Bacteroides_vulgatus_ATCC_8482                     46            0.311947
Blautia_hydrogenotrophica_DSM_10507                48            0.247251
Bacteroides_thetaiotaomicron_VPI_5482              51            0.277849
Collinsella_aerofaciens_ATCC_25986                 51            0.393160
Eubacterium_rectale_ATCC_33656                     53            0.195458
Desulfovibrio_piger_ATCC_29098                     53            0.371592
Eggerthella_lenta_DSM_2243                         58            0.428910
Bacteroides_ovatus_ATCC_8483                       59            0.248470
Faecalibacterium_prausnitzii_A2_165                60            0.266212
Clostridium_hiranonis_TO_931_DSM_13275             62            0.274695

In [26]:
closeness_centrality_met = centrality_metrics_SP["closeness (1/data)"]

In [27]:
net = networks.cooperation_network(network_data,closeness_centrality_met=closeness_centrality_met)
net.show("network_file.html")

network_file.html

In [28]:
net = networks.cooperation_network(network_data,closeness_centrality_met=closeness_centrality_met,cutoff=3)
net.show("network_file.html")

network_file.html

## Cooperation based on FREQUENCY

In [30]:

network_data = networks.cooperation_network_data(results,metabolomics_mets_only=False,use_count=False)

**Network topological properties**


- **Betweeness_centrality**: Sum of shortest paths that pass through node i
- **Degree centrality**: The fraction of nodes that node i is connected to. 
- **Eigenvector centrality**: Higher if node i is connected to other well connected notes.

In [31]:
centrality_metrics_SP = networks.cooperation_centrality_metrics(network_data).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Blautia_hydrogenotrophica_DSM_10507,0.000000,0.052810
Eubacterium_rectale_ATCC_33656,0.000000,0.057766
Bacteroides_uniformis_ATCC_8492,0.000000,0.060041
Bacteroides_ovatus_ATCC_8483,0.000000,0.064913
Bacteroides_thetaiotaomicron_VPI_5482,0.011111,0.066250
Bacteroides_vulgatus_ATCC_8482,0.000000,0.066685
Desulfovibrio_piger_ATCC_29098,0.000000,0.081876
Faecalibacterium_prausnitzii_A2_165,0.122222,0.082315
Collinsella_aerofaciens_ATCC_25986,0.000000,0.087767
Clostridium_hiranonis_TO_931_DSM_13275,0.155556,0.096091
Eggerthella_lenta_DSM_2243,0.122222,0.141856

In [32]:
centrality_metrics_notSP = networks.cooperation_centrality_metrics(network_data,SP_centrality=False).sort_values("degree (data)")
centrality_metrics_notSP

                                        degree (data)  eigenvector (data)
Eubacterium_rectale_ATCC_33656               1.260890            0.194319
Blautia_hydrogenotrophica_DSM_10507          1.267666            0.174569
Desulfovibrio_piger_ATCC_29098               1.273208            0.303781
Bacteroides_uniformis_ATCC_8492              1.479788            0.224599
Collinsella_aerofaciens_ATCC_25986           1.518716            0.324708
Bacteroides_thetaiotaomicron_VPI_5482        1.576720            0.277090
Bacteroides_vulgatus_ATCC_8482               1.621429            0.245786
Bacteroides_ovatus_ATCC_8483                 1.888901            0.220493
Eggerthella_lenta_DSM_2243                   2.135781            0.493814
Faecalibacterium_prausnitzii_A2_165          2.175299            0.315881
Clostridium_hiranonis_TO_931_DSM_13275       2.482216            0.392637

In [33]:
closeness_centrality_met = centrality_metrics_notSP["degree (data)"]

In [34]:
closeness_centrality_met["Clostridium_hiranonis_TO_931_DSM_13275"]

np.float64(2.4822159423909422)

In [35]:
net = networks.cooperation_network(network_data,closeness_centrality_met=closeness_centrality_met)
net.show("network_file.html")

network_file.html

In [36]:
net = networks.cooperation_network(network_data,closeness_centrality_met=closeness_centrality_met,cutoff=0.1)
net.show("network_file.html")

network_file.html