# Competition networks

In [1]:
import pandas as pd
import json
import seaborn as sns
import numpy as np

import networkx as nx

from pyvis.network import Network

import sys

sys.path.append("../functions/")

import networks

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
with open("../data/Venturelli2018/generated/metid2metname.json") as json_file:
    metid2metname = json.load(json_file)

results = pd.read_csv("../output/Venturelli2018/results_steadiercom/NONE_abundance.tsv",sep="\t")

results["mass_rate*frequency"] = results["frequency"]*results["mass_rate"]

## Competition for nutrients in ENVIRONMENT (only compounds in metabolomics!!): consumption overlap

### Overlap count (compound consumed with high frequency)

In [4]:
results_env = results[(results.donor=="environment")]

**Count (cutoff frequency=0.5!!)**

In [5]:
network_data = networks.competition_network_data(results_env,freq_cutoff=0.5)

**Network topological properties**


- **Betweeness_centrality**: Sum of shortest paths that pass through node i
- **Degree centrality**: The fraction of nodes that node i is connected to. 
- **Eigenvector centrality**: Higher if node i is connected to other well connected notes.

In [6]:
centrality_metrics_SP = networks.competition_centrality_metrics(network_data).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Eggerthella_lenta_DSM_2243,0.000000,4.849885
Bacteroides_uniformis_ATCC_8492,0.000000,5.284127
Bacteroides_thetaiotaomicron_VPI_5482,0.000000,6.290564
Desulfovibrio_piger_ATCC_29098,0.000000,6.400813
Blautia_hydrogenotrophica_DSM_10507,0.000000,6.444863
Bacteroides_vulgatus_ATCC_8482,0.000000,6.614173
Collinsella_aerofaciens_ATCC_25986,0.000000,6.845966
Bacteroides_ovatus_ATCC_8483,0.022222,7.558488
Clostridium_hiranonis_TO_931_DSM_13275,0.044444,7.610785
Faecalibacterium_prausnitzii_A2_165,0.000000,8.012487
Eubacterium_rectale_ATCC_33656,0.011111,8.297414

In [7]:
networks.competition_centrality_metrics(network_data,SP_centrality=False).sort_values("degree (data)")

                                        degree (data)  eigenvector (data)
Eggerthella_lenta_DSM_2243                       51.0            0.212501
Bacteroides_uniformis_ATCC_8492                  56.0            0.229903
Bacteroides_thetaiotaomicron_VPI_5482            68.0            0.276355
Bacteroides_vulgatus_ATCC_8482                   69.0            0.281894
Blautia_hydrogenotrophica_DSM_10507              72.0            0.301857
Desulfovibrio_piger_ATCC_29098                   72.0            0.300892
Collinsella_aerofaciens_ATCC_25986               73.0            0.300516
Bacteroides_ovatus_ATCC_8483                     78.0            0.310859
Clostridium_hiranonis_TO_931_DSM_13275           83.0            0.339456
Faecalibacterium_prausnitzii_A2_165              87.0            0.355232
Eubacterium_rectale_ATCC_33656                   91.0            0.368964

**Network**

In [8]:
closeness_centrality_met = centrality_metrics_SP["closeness (1/data)"].to_dict()

net = networks.competition_network(network_data,closeness_centrality_met,cutoff=0)
net.show("network_file.html")

network_file.html

**Cutoff=7!!**

In [9]:
centrality_metrics_SP = networks.competition_centrality_metrics(network_data,cutoff=7).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Eggerthella_lenta_DSM_2243,0.000000,0.000000
Bacteroides_uniformis_ATCC_8492,0.000000,3.687744
Bacteroides_vulgatus_ATCC_8482,0.000000,4.922004
Collinsella_aerofaciens_ATCC_25986,0.000000,5.071304
Bacteroides_thetaiotaomicron_VPI_5482,0.044444,5.089005
Blautia_hydrogenotrophica_DSM_10507,0.000000,5.236043
Desulfovibrio_piger_ATCC_29098,0.000000,5.244604
Bacteroides_ovatus_ATCC_8483,0.133333,5.735026
Clostridium_hiranonis_TO_931_DSM_13275,0.111111,6.319149
Faecalibacterium_prausnitzii_A2_165,0.088889,6.535833
Eubacterium_rectale_ATCC_33656,0.155556,7.019038

In [10]:
networks.competition_centrality_metrics(network_data,SP_centrality=False,cutoff=7).sort_values("degree (data)")

                                        degree (data)  eigenvector (data)
Eggerthella_lenta_DSM_2243                        0.0        4.198209e-27
Bacteroides_uniformis_ATCC_8492                  17.0        5.237260e-02
Bacteroides_vulgatus_ATCC_8482                   26.0        1.281079e-01
Bacteroides_thetaiotaomicron_VPI_5482            35.0        1.270989e-01
Collinsella_aerofaciens_ATCC_25986               44.0        3.390709e-01
Bacteroides_ovatus_ATCC_8483                     45.0        2.005441e-01
Blautia_hydrogenotrophica_DSM_10507              47.0        3.579933e-01
Desulfovibrio_piger_ATCC_29098                   47.0        3.569281e-01
Clostridium_hiranonis_TO_931_DSM_13275           58.0        3.959824e-01
Faecalibacterium_prausnitzii_A2_165              62.0        4.280324e-01
Eubacterium_rectale_ATCC_33656                   73.0        4.625297e-01

In [11]:
closeness_centrality_met = centrality_metrics_SP["closeness (1/data)"].to_dict()

net = networks.competition_network(network_data,closeness_centrality_met,cutoff=7)
net.show("network_file.html")

network_file.html

## Competition for compounds from other members: consumption overlap (NB!! All metabolites)

### Overlap count (compound consumed with high frequency)

In [12]:
results_env = results[(results.donor!="environment") & (results.receiver!="environment")]

**Count (cutoff frequency=0.1!!)**

In [13]:
network_data = networks.competition_network_data(results_env,freq_cutoff=0.1,metabolomics_mets_only=False)

**Network topological properties**


- **Betweeness_centrality**: Sum of shortest paths that pass through node i
- **Degree centrality**: The fraction of nodes that node i is connected to. 
- **Eigenvector centrality**: Higher if node i is connected to other well connected notes.

In [14]:
centrality_metrics_SP = networks.competition_centrality_metrics(network_data).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Faecalibacterium_prausnitzii_A2_165,0.000000,2.429150
Desulfovibrio_piger_ATCC_29098,0.000000,2.830189
Eggerthella_lenta_DSM_2243,0.000000,2.912621
Bacteroides_uniformis_ATCC_8492,0.000000,2.955665
Clostridium_hiranonis_TO_931_DSM_13275,0.000000,3.278689
Bacteroides_ovatus_ATCC_8483,0.000000,3.296703
Eubacterium_rectale_ATCC_33656,0.000000,3.305785
Bacteroides_thetaiotaomicron_VPI_5482,0.011111,3.726708
Blautia_hydrogenotrophica_DSM_10507,0.029630,4.000000
Collinsella_aerofaciens_ATCC_25986,0.162963,4.195804
Bacteroides_vulgatus_ATCC_8482,0.074074,4.301075

In [15]:
networks.competition_centrality_metrics(network_data,SP_centrality=False).sort_values("degree (data)")

                                        degree (data)  eigenvector (data)
Faecalibacterium_prausnitzii_A2_165              22.0            0.180044
Desulfovibrio_piger_ATCC_29098                   27.0            0.227867
Eggerthella_lenta_DSM_2243                       29.0            0.246814
Bacteroides_uniformis_ATCC_8492                  31.0            0.272725
Eubacterium_rectale_ATCC_33656                   34.0            0.285560
Bacteroides_ovatus_ATCC_8483                     35.0            0.305605
Clostridium_hiranonis_TO_931_DSM_13275           36.0            0.305203
Blautia_hydrogenotrophica_DSM_10507              42.0            0.340523
Bacteroides_thetaiotaomicron_VPI_5482            42.0            0.356648
Collinsella_aerofaciens_ATCC_25986               43.0            0.343440
Bacteroides_vulgatus_ATCC_8482                   47.0            0.388810

**Network**

In [16]:
closeness_centrality_met = centrality_metrics_SP["closeness (1/data)"].to_dict()

net = networks.competition_network(network_data,closeness_centrality_met,cutoff=0)
net.show("network_file.html")

network_file.html

**Cutoff=4!!**

In [17]:
cutoff=4

In [18]:
centrality_metrics_SP = networks.competition_centrality_metrics(network_data,cutoff=cutoff).sort_values("closeness (1/data)")
centrality_metrics_SP

,betweeness (1/data),closeness (1/data)
Eggerthella_lenta_DSM_2243,0.000000,0.000000
Faecalibacterium_prausnitzii_A2_165,0.000000,0.000000
Desulfovibrio_piger_ATCC_29098,0.000000,1.944304
Bacteroides_uniformis_ATCC_8492,0.000000,2.232558
Bacteroides_ovatus_ATCC_8483,0.000000,2.370370
Clostridium_hiranonis_TO_931_DSM_13275,0.000000,2.526316
Eubacterium_rectale_ATCC_33656,0.000000,2.568562
Collinsella_aerofaciens_ATCC_25986,0.055556,2.792727
Bacteroides_thetaiotaomicron_VPI_5482,0.055556,2.965251
Blautia_hydrogenotrophica_DSM_10507,0.100000,3.059761
Bacteroides_vulgatus_ATCC_8482,0.300000,3.783251

In [19]:
networks.competition_centrality_metrics(network_data,SP_centrality=False,cutoff=cutoff).sort_values("degree (data)")

                                        degree (data)  eigenvector (data)
Eggerthella_lenta_DSM_2243                        0.0        2.468374e-24
Faecalibacterium_prausnitzii_A2_165               0.0        2.468374e-24
Desulfovibrio_piger_ATCC_29098                   10.0        1.505339e-01
Bacteroides_uniformis_ATCC_8492                  11.0        2.353643e-01
Bacteroides_ovatus_ATCC_8483                     12.0        2.604411e-01
Clostridium_hiranonis_TO_931_DSM_13275           15.0        2.985762e-01
Eubacterium_rectale_ATCC_33656                   15.0        2.759179e-01
Collinsella_aerofaciens_ATCC_25986               20.0        3.037785e-01
Blautia_hydrogenotrophica_DSM_10507              25.0        3.590385e-01
Bacteroides_thetaiotaomicron_VPI_5482            25.0        4.035481e-01
Bacteroides_vulgatus_ATCC_8482                   39.0        5.520816e-01

In [20]:
closeness_centrality_met = centrality_metrics_SP["closeness (1/data)"].to_dict()

net = networks.competition_network(network_data,closeness_centrality_met,cutoff=cutoff)
net.show("network_file.html")

network_file.html