In [1]:
import pandas as pd

In [32]:
BH_minus = pd.read_csv("../output/Venturelli2018/results_steadiercom/results_growth_abundance/BH_minus.tsv",
                      sep="\t")

In [33]:
BH_minus[BH_minus.donor=="environment"]

,donor,receiver,compound,mass_rate,rate,frequency,community,medium
0,environment,Bacteroides_uniformis_ATCC_8492,M_malt__91__e__93__,2.724288e-01,0.795887,0.98,BH-,LB_extend
1,environment,Bacteroides_uniformis_ATCC_8492,M_cellb__91__e__93__,1.916689e-01,0.559951,0.02,BH-,LB_extend
5,environment,Faecalibacterium_prausnitzii_A2_165,M_ribflv__91__e__93__,1.243466e-01,0.330390,1.00,BH-,LB_extend
8,environment,Bacteroides_thetaiotaomicron_VPI_5482,M_glu_L__91__e__93__,7.518355e-02,0.514529,0.28,BH-,LB_extend
11,environment,Faecalibacterium_prausnitzii_A2_165,M_pyr__91__e__93__,5.825845e-02,0.669222,0.48,BH-,LB_extend
...,...,...,...,...,...,...,...,...
1023,environment,Prevotella_copri_CB7_DSM_18205,M_met_L__91__e__93__,4.663468e-07,0.000003,1.00,BH-,LB_extend
1028,environment,Desulfovibrio_piger_ATCC_29098,M_pydx__91__e__93__,4.145160e-07,0.000002,1.00,BH-,LB_extend
1040,environment,Prevotella_copri_CB7_DSM_18205,M_uri__91__e__93__,2.807933e-07,0.000001,0.04,BH-,LB_extend
1041,environment,Eubacterium_rectale_ATCC_33656,M_nh4__91__e__93__,2.744332e-07,0.000015,0.02,BH-,LB_extend
1048,environment,Desulfovibrio_piger_ATCC_29098,M_so4__91__e__93__,2.382095e-07,0.000002,1.00,BH-,LB_extend

In [26]:
media_db_gut = pd.read_csv("../data/Venturelli2018/generated/media_db.tsv",sep="\t")
media_db_gut

       medium                   compound
0   LB_extend    R_EX_glc_D__91__e__93__
1   LB_extend     R_EX_succ__91__e__93__
2   LB_extend     R_EX_ptrc__91__e__93__
3   LB_extend  R_EX_cobalt2__91__e__93__
4   LB_extend    R_EX_2obut__91__e__93__
..        ...                        ...
76  LB_extend      R_EX_gly__91__e__93__
77  LB_extend    R_EX_sheme__91__e__93__
78  LB_extend    R_EX_glu_L__91__e__93__
79  LB_extend      R_EX_thm__91__e__93__
80  LB_extend    R_EX_ala_L__91__e__93__

[81 rows x 2 columns]

In [27]:
[cpd for cpd in media_db_gut.compound.values if "_arg_" in cpd]

['R_EX_arg_L__91__e__93__']

In [28]:
[cpd for cpd in media_db_gut.compound.values if "_cys_" in cpd]

['R_EX_cys_L__91__e__93__']

In [29]:
[cpd for cpd in media_db_gut.compound.values if "_succ_" in cpd]

['R_EX_succ__91__e__93__']

In [30]:
[cpd for cpd in media_db_gut.compound.values if "_mqn8_" in cpd]

['R_EX_mqn8__91__e__93__']

In [25]:
[cpd for cpd in media_db_gut.compound.values if "_q8_" in cpd]

['R_EX_q8__91__e__93__']

In [31]:
[cpd for cpd in media_db_gut.compound.values if "_mqn8_" in cpd]

['R_EX_mqn8__91__e__93__']